#name of the workflow
name: example workflow

#events that will trigger the workflow
on:
  push:
   branches:
    - master
  pull_request:
   branches:
    - master
 #This specifies that the workflow can also be manually triggered using the GitHub Actions workflow dispatch UI or API.   
  workflow_dispatch:

#list of jobs to perform when the event is triggered
jobs:
  hello:
   runs-on: windows-latest
   steps:
    - uses: actions/checkout@v2
    - name: example
      run: echo "hey"
      shell: powershell

  goodbye:
    runs-on: windows-latest
    steps:
      - name: goodbye world
        run: echo "goodbye"
        shell: powershell
